# Generated by Django 4.1.7 on 2023-04-26 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_price_usd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_usd",
        ),
        migrations.AddField(
            model_name="product",
            name="price_eur",
            field=models.DecimalField(
                decimal_places=5, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
